name: Build
on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .gitignore
      - 'docs/**'
      - 'theme/**'
      - 'po/**'
      - book.toml
      - .github/workflows/docs.yaml
      - container/Dockerfile
      - .github/workflows/deploy-image.yml
  pull_request:
    paths-ignore:
      - '**.md'
      - .gitignore
      - 'docs/**'
      - 'theme/**'
      - 'po/**'
      - book.toml
      - .github/workflows/docs.yaml
      - container/Dockerfile
      - .github/workflows/deploy-image.yml

jobs:
  query:
    runs-on: ubuntu-latest
    outputs:
      linux: ${{ steps.query.outputs.linux }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Query available board configs
        id: query
        run: |
          echo "linux=$(./bsp json profile linux)" >> $GITHUB_OUTPUT

  build_linux:
    needs: query
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: [ linux ]
        profiles: ${{fromJSON(needs.query.outputs.linux)}}
    steps:
      - name: Build
        uses: radxa-repo/bsp@main
        with:
          target: ${{ matrix.targets }}
          edition: ${{ matrix.profiles }}
          artifacts: true
      - name: List output files
        run: ls -la .output
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: .output/**
